---

- debug: var=aws
- debug: var=shelleg

- ec2_key:
    name: "{{ aws.ec2.ssh_key }}"
    region: "{{ aws.ec2.region }}"
    state: present
  register: awskey

- debug:
   msg: 'private key is {{ awskey.key.private_key }}'
  when: awskey.changed

- local_action: copy content="{{ awskey.key.private_key }}" dest="~/.ssh/id_rsa_{{ aws.ec2.ssh_key }}"
  when: awskey.changed

- file:
    path: "~/.ssh/id_rsa_{{ aws.ec2.ssh_key }}"
    mode: 0600
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  when: awskey.changed