# -*- mode:1
# : ruby -*-
# # vi: set ft=ruby :

ansible_verbosity = '-vvv'
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# This example shows how Vagrant variables can be loaded from Ansible's variables,
# and a demonstration of using the DEFAULTS, which will be called automatically
# when running from `deploy.sh vagrant`.
# It makes sure that configuration will only be done in one place,
# Follow this method on future changes to this file.
# CONF_GENERAL = YAML.load( File.open( ansible_vars + '/' + '00_general', File::RDONLY ).read )

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
    end
  end
end
