---

- name: "Generate aws key pair"
  include: aws-key.yml
  tags:
  - awskey

- name: "Create aws vpc"
  include: aws-vpc.yml
  tags:
  - awsvpc

- name: "Create aws security group"
  include: aws-sg.yml
  tags:
  - awssg

- name: "Create ec2 instances"
  include: aws-instances.yml
  tags:
  - awsinstances
