---
- ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ ec2_region }}"
    filters:
      subnet-id: "{{ ec2_subnet_ids }}"
  register: subnet_facts

- debug: var=subnet_facts.subnets[0].cidr_block

- set_fact:
    nfs_allowed_subnet: "{{ subnet_facts.subnets[0].cidr_block }}"