---
# tasks file for ansible-role-infra-init

- name: "Create infra vagrant boxes"
  command: "vagrant up"
  args:
      chdir: "{{ shelleg.vagrant_dir }}"
  with_items:
  - "{{ shelleg_hosts.infra }}"
  when: clean is undefined or skip_create is defined

- name: "Add infra nodes to Ansible inventory"
  add_host:
    name: "{{ shelleg.prefix }}-{{ item.cname }}"
    ansible_host: "{{ item.ip }}"
    ansible_port: "{{ item.ssh_port }}"
    ansible_user: "{{ item.user }}"
    ansible_ssh_private_key_file: "{{ shelleg.vagrant_dir }}/.vagrant/machines/{{ shelleg.prefix }}-{{ item.cname }}/virtualbox/private_key"
    groups: "{{ shelleg_hosts.infra_group_name }}"
  with_items:
  - "{{ shelleg_hosts.infra }}"

