---
- fail: "msg=\"This role requires shelleg context - read more at http:// url to docs\""
  when: "shelleg is undefined or shelleg_hosts is undefined"

- name: "Prep for consul quarum instantiation if wanted||needed in the future"
  debug: var=item.consul_leader
  with_items:
    - "{{ shelleg_hosts.infra }}"

- name: "set consul leader facts"
  set_fact:
    consul_leader_hostname: "{{ item.cname }}-{{ consul_service_name }}"
    consul_leader_ip: "{{ item.ip }}"
  when: ("{{ item.consul_leader }}" == "true")
  with_items:
    - "{{ shelleg_hosts.infra }}"

- debug: var=consul_leader_ip
- debug: var=consul_leader_hostname
- debug: var=ansible_docker0.ipv4.address

- name: "create systemd service file"
  template:
    dest: "/etc/systemd/system/{{ consul_service_name }}.service"
    src: "templates/systemd-container.service.j2"
  register: systemd_config

- name: "reload daemon"
  shell: systemctl daemon-reload
  when: systemd_config.changed

- name: "restart service"
  service:
    name: "{{ consul_service_name }}"
    state: restarted
  when: systemd_config.changed

- name: "enable service"
  service:
    name: "{{ consul_service_name }}"
    state: started
    enabled: yes
