---
# Set swarm and set leader
- name: Register Leader
  shell: docker swarm init --advertise-addr {{ shelleg_hosts.swarm.swarm_managers[0].ip }}
  register: swarmTokenRaw

- name: Print Token
  debug: var=swarmTokenRaw.stdout_lines[5]

- name: Set Token and Clean the prefix
  set_fact:
    swarmToken_tmp: "{{ swarmTokenRaw.stdout_lines[5] | regex_replace('    --token ', '') }}"

- name: Set Token and Clean last 3 characters
  set_fact:
    swarmToken: "{{ swarmToken_tmp | regex_replace('.{2}$', '') }}"

#- name: Print Token
#  debug:  msg="swarmToken={{ swarmToken }}"