---
- hosts: localhost
  #become: yes
  #become_user: root
  #gather_facts: no
  vars:
    vagrant: true
  roles:
    - { role: cluster-init }
    #- { role: ../site-roles/ }
    #- { role: ../site-roles/ }
    #- { role: ../site-roles/ }
    #- { role: ../site-roles/ }

- hosts: swarm-cluster-nodes
  become: yes
  become_user: root 
  tasks:
    - debug: msg="Install stuff common to all nodes cicd-manager, cicd-node, cicd-node2"

- hosts: cicd-manager
  become: yes
  become_user: root
  tasks:
    - debug: msg="Install stuff common to cicd-manager"

- hosts: cicd-node
  become: yes
  become_user: root
  tasks:
    - debug: msg="Install stuff common to cicd-node"

- hosts: cicd-node2
  become: yes
  become_user: root
  tasks:
    - debug: msg="Install stuff common to cicd-node2"
